export const DUMMY_CANDIDATES = [
    {
        id: "1",
        name: "Jane Doe",
        party: "Progressive Alliance",
        position: "Student Body President",
        election_id: "1",
        image: "https://i.pravatar.cc/150?u=1",
    },
    {
        id: "2",
        name: "John Smith",
        party: "Future Leaders",
        position: "Student Body President",
        election_id: "1",
        image: "https://i.pravatar.cc/150?u=2",
    },
    {
        id: "3",
        name: "Alice Johnson",
        party: "Unity Party",
        position: "Vice President",
        election_id: "1",
        image: "https://i.pravatar.cc/150?u=3",
    },
    {
        id: "4",
        name: "Robert Brown",
        party: "Progressive Alliance",
        position: "Treasurer",
        election_id: "1",
        image: "https://i.pravatar.cc/150?u=4",
    },
    {
        id: "5",
        name: "Emily Davis",
        party: "Future Leaders",
        position: "Secretary",
        election_id: "1",
        image: "https://i.pravatar.cc/150?u=5",
    },
] as any[];

export const DUMMY_PARTIES = [
    {
        id: "1",
        name: "Progressive Alliance",
        abbreviation: "PA",
        founded: "2020",
        description: "Advocating for student rights and campus improvements.",
        logo: "https://via.placeholder.com/50",
    },
    {
        id: "2",
        name: "Future Leaders",
        abbreviation: "FL",
        founded: "2019",
        description: "Building the leaders of tomorrow through innovation.",
        logo: "https://via.placeholder.com/50",
    },
    {
        id: "3",
        name: "Unity Party",
        abbreviation: "UP",
        founded: "2021",
        description: "Uniting students from all backgrounds.",
        logo: "https://via.placeholder.com/50",
    },
    {
        id: "4",
        name: "Green Campus Initiative",
        abbreviation: "GCI",
        founded: "2022",
        description: "Promoting sustainability and eco-friendly practices.",
        logo: "https://via.placeholder.com/50",
    },
    {
        id: "5",
        name: "Tech Innovators",
        abbreviation: "TI",
        founded: "2023",
        description: "Leveraging technology for better student services.",
        logo: "https://via.placeholder.com/50",
    },
] as any[];

export const DUMMY_VOTERS = [
    {
        id: "1",
        first_name: "Michael",
        last_name: "Scott",
        nin: "NIN123456789",
        email: "michael.scott@example.com",
        state_of_residence: "Scranton",
        status: "Verified",
    },
    {
        id: "2",
        name: "Dwight Schrute", // Some components might use name or first_name/last_name
        first_name: "Dwight",
        last_name: "Schrute",
        nin: "NIN987654321",
        email: "dwight.schrute@example.com",
        state_of_residence: "Farms",
        status: "Verified",
    },
    {
        id: "3",
        first_name: "Jim",
        last_name: "Halpert",
        nin: "NIN456789123",
        email: "jim.halpert@example.com",
        state_of_residence: "Philly",
        status: "Pending",
    },
    {
        id: "4",
        first_name: "Pam",
        last_name: "Beesly",
        nin: "NIN321654987",
        email: "pam.beesly@example.com",
        state_of_residence: "Scranton",
        status: "Verified",
    },
    {
        id: "5",
        first_name: "Ryan",
        last_name: "Howard",
        nin: "NIN741852963",
        email: "ryan.howard@example.com",
        state_of_residence: "New York",
        status: "Suspended",
    },
] as any[];

export const DUMMY_ELECTIONS = [
    {
        election_id: 1,
        title: "2024 Student Government Elections",
        start_date: "2024-11-20",
        end_date: "2024-12-05",
        is_active: true,
        description: "Annual election for student body representatives.",
    },
    {
        election_id: 2,
        title: "Faculty Board Elections",
        start_date: "2024-12-01",
        end_date: "2024-12-15",
        is_active: true,
        description: "Election for faculty board members.",
    },
    {
        election_id: 3,
        title: "Department Representative",
        start_date: "2025-01-10",
        end_date: "2025-01-20",
        is_active: false,
        description: "Choose your department representatives.",
    },
    {
        election_id: 4,
        title: "Sports Committee Election",
        start_date: "2023-05-10",
        end_date: "2023-05-20",
        is_active: false,
        description: "Election for the new sports committee.",
    },
    {
        election_id: 5,
        title: "Alumni Association President",
        start_date: "2025-03-01",
        end_date: "2025-03-15",
        is_active: false,
        description: "Vote for the next Alumni Association President.",
    },
] as any[];

export const DUMMY_POSITIONS = [
    {
        position_id: 1,
        title: "President",
        description: "Head of the student body",
        election_id: 1,
    },
    {
        position_id: 2,
        title: "Vice President",
        description: "Deputy head of the student body",
        election_id: 1,
    },
    {
        position_id: 3,
        title: "Secretary",
        description: "Keeper of records",
        election_id: 1,
    },
    {
        position_id: 4,
        title: "Treasurer",
        description: "Manager of funds",
        election_id: 1,
    },
    {
        position_id: 5,
        title: "Public Relations Officer",
        description: "Spokesperson for the student body",
        election_id: 1,
    },
] as any[];
